import re


class InvestigationReport:
    """
    Converts the raw TraceAI investigation result
    into a clean, structured diagnostic report.

    The deterministic root-cause analysis remains
    authoritative.

    LLM output is treated as explanatory analysis
    and is independently checked for citation and
    claim grounding.
    """

    def build(self, investigation: dict) -> dict:
        root_cause = investigation["root_cause"]
        confidence = investigation["evidence_confidence"]
        citation_verification = investigation["citation_verification"]
        claim_verification = investigation["claim_verification"]

        cleaned_analysis = self._clean_llm_analysis(
            investigation["analysis"]
        )

        return {
            "query": investigation["query"],

            "root_cause": {
                "name": root_cause["root_cause"],
                "explanation": root_cause["explanation"],
                "confidence": root_cause["confidence"],
                "support_score": root_cause["support_score"],
            },

            "evidence_summary": {
                "observed": root_cause.get("observed_evidence", 0),
                "code": root_cause.get("code_evidence", 0),
                "stacktrace": root_cause.get("stacktrace_evidence", 0),
                "supporting_sources": root_cause.get(
                    "supporting_sources", 0
                ),
            },

            "grounded_confidence": {
                "label": confidence["confidence"],
                "score": confidence["score"],
                "observed_root_cause": confidence[
                    "observed_root_cause"
                ],
                "stacktrace_confirmation": confidence[
                    "stacktrace_confirmation"
                ],
                "code_confirmation": confidence[
                    "code_confirmation"
                ],
                "failure_confirmation": confidence[
                    "failure_confirmation"
                ],
            },

            "citation_verification": {
                "total": citation_verification[
                    "total_citations"
                ],
                "verified": citation_verification[
                    "verified_citations"
                ],
                "coverage": citation_verification[
                    "citation_coverage"
                ],
                "all_verified": citation_verification[
    "all_verified"
],

"status": citation_verification[
    "status"
],
            },

            "claim_verification": {
                "total": claim_verification[
                    "total_claims"
                ],
                "supported": claim_verification[
                    "supported_count"
                ],
                "unsupported": claim_verification[
                    "unsupported_count"
                ],
                "coverage": claim_verification[
                    "claim_coverage"
                ],
                "has_unsupported_claims": claim_verification[
                    "has_unsupported_claims"
                ],
                "unsupported_claims": claim_verification[
                    "unsupported_claims"
                ],
            },

            "llm_analysis": cleaned_analysis,

            "evidence": investigation["evidence"],
        }

    @staticmethod
    def _clean_llm_analysis(analysis: str) -> str:
        """
        Removes sections that TraceAI does not allow
        the LLM to control.

        Confidence is calculated independently by
        EvidenceConfidence and therefore any LLM-generated
        confidence section is removed.
        """

        if not analysis:
            return analysis

        # Remove any confidence section generated by the LLM.
        cleaned = re.sub(
            r"\n*###\s*5\.\s*CONFIDENCE\b.*",
            "",
            analysis,
            flags=re.IGNORECASE | re.DOTALL,
        )

        # Also remove alternative confidence headings
        # if the model changes the numbering.
        cleaned = re.sub(
            r"\n*###\s*CONFIDENCE\b.*",
            "",
            cleaned,
            flags=re.IGNORECASE | re.DOTALL,
        )

        return cleaned.strip()