import re


class CitationVerifier:
    """
    Verifies whether citations generated by the LLM
    correspond to retrieved evidence.

    This verifies citation correctness, not whether
    the cited evidence semantically proves the claim.
    """

    CITATION_PATTERN = re.compile(
        r"\[([^\[\]:]+):([^\[\]]+)\]"
    )

    def extract_citations(
        self,
        analysis: str
    ) -> list[dict]:

        citations = []

        for match in self.CITATION_PATTERN.finditer(
            analysis
        ):
            source_file = match.group(1).strip()
            location = match.group(2).strip()

            citations.append({
                "source_file": source_file,
                "location": location,
                "raw": match.group(0),
            })

        return citations

    def verify(
        self,
        analysis: str,
        evidence: list[dict]
    ) -> dict:

        citations = self.extract_citations(
            analysis
        )

        verified = []
        unverified = []

        for citation in citations:

            source_file = citation["source_file"]
            location = citation["location"]

            matched_evidence = None

            for item in evidence:

                if (
                    self._normalize_path(
                        item["source_file"]
                    )
                    ==
                    self._normalize_path(
                        source_file
                    )
                    and
                    self._normalize_location(
                        item["location"]
                    )
                    ==
                    self._normalize_location(
                        location
                    )
                ):
                    matched_evidence = item
                    break

            if matched_evidence:

                verified.append({
                    **citation,
                    "status": "verified",
                    "evidence": matched_evidence,
                })

            else:

                unverified.append({
                    **citation,
                    "status": "unverified",
                })

        total = len(citations)
        verified_count = len(verified)

        coverage = (
            verified_count / total
            if total > 0
            else 0.0
        )

        # No citations is NOT considered a pass.
        if total == 0:
            status = "FAIL"
            all_verified = False

        elif verified_count == total:
            status = "PASS"
            all_verified = True

        else:
            status = "WARNING"
            all_verified = False

        return {
            "citations": citations,
            "verified": verified,
            "unverified": unverified,
            "total_citations": total,
            "verified_citations": verified_count,
            "citation_coverage": coverage,
            "has_unverified_citations": (
                len(unverified) > 0
            ),
            "status": status,
            "all_verified": all_verified,
        }

    @staticmethod
    def _normalize_path(path: str) -> str:
        return (
            path
            .replace("\\", "/")
            .strip()
            .lower()
        )

    @staticmethod
    def _normalize_location(
        location: str
    ) -> str:

        return (
            location
            .replace("\\", "/")
            .strip()
            .lower()
        )